# the JAVA name of the module
module.java = com.s8.core.db.cobalt

# dependencies (by JAVA name)
dependencies = \
	S8-meta-env, \
	S8-meta-api, \
	S8-base-io-XML, \
	S8-base-io-bytes, \
	S8-base-io-JSON, \
	S8-core-arch-silicon, \
	S8-core-arch-titanium, \
	S8-bohr-protocol, \
	S8-bohr-io-lithium, \
	
# the {jar file / project directory } name (for pathname composition)
target = S8-core-db-cobalt